.TH "/home/jihoon/Develop/PaScaL_TDMA/examples Directory Reference" 3 "Wed Apr 26 2023" "PaScaL_TDMA2.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jihoon/Develop/PaScaL_TDMA/examples Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBglobal\&.f90\fP"
.br
.RI "This file contains a module of global parameters for the example problem of PaScaL_TDMA\&. "
.ti -1c
.RI "file \fBmain\&.f90\fP"
.br
.RI "This file contains the main subroutines for an example problem of PaScaL_TDMA\&. "
.ti -1c
.RI "file \fBmpi_subdomain\&.f90\fP"
.br
.RI "This file contains a module of subdomains for the example problem of PaScaL_TDMA\&. "
.ti -1c
.RI "file \fBmpi_topology\&.f90\fP"
.br
.RI "This file contains a module of communication topology for the example problem of PaScaL_TDMA\&. "
.ti -1c
.RI "file \fBsolve_theta\&.f90\fP"
.br
.RI "This file contains a solver subroutine for the example problem of PaScaL_TDMA\&. "
.in -1c
