.TH "/home/jihoon/Develop/PaScaL_TDMA/src Directory Reference" 3 "Wed Apr 26 2023" "PaScaL_TDMA2.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jihoon/Develop/PaScaL_TDMA/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBnvtx\&.f90\fP"
.br
.ti -1c
.RI "file \fBpara_range\&.f90\fP"
.br
.RI "The para_range function assigns the computing range to each MPI process\&. "
.ti -1c
.RI "file \fBpascal_tdma\&.f90\fP"
.br
.RI "PaScaL_TDMA - Parallel and Scalable Library for TriDiagonal Matrix Algorithm\&. "
.ti -1c
.RI "file \fBpascal_tdma_cuda\&.f90\fP"
.br
.ti -1c
.RI "file \fBtdmas\&.f90\fP"
.br
.RI "Tridiagonal matrix (TDM) solvers using the Thomas algorithm\&. "
.ti -1c
.RI "file \fBtdmas_cuda\&.f90\fP"
.br
.in -1c
