.TH "nvtx::nvtxrangepush" 3 "Wed Apr 26 2023" "PaScaL_TDMA2.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nvtx::nvtxrangepush
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBnvtxrangepusha\fP (name)"
.br
.ti -1c
.RI "subroutine \fBnvtxrangepushex\fP (event)"
.br
.in -1c
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "subroutine nvtx::nvtxrangepush::nvtxrangepusha (character(kind=c_char), dimension(256) name)"

.SS "subroutine nvtx::nvtxrangepush::nvtxrangepushex (type(\fBnvtxeventattributes\fP) event)"


.SH "Author"
.PP 
Generated automatically by Doxygen for PaScaL_TDMA2\&.0 from the source code\&.
