.TH "nvtx::nvtxeventattributes" 3 "Wed Apr 26 2023" "PaScaL_TDMA2.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nvtx::nvtxeventattributes
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer(c_int16_t) \fBversion\fP =1"
.br
.ti -1c
.RI "integer(c_int16_t) \fBsize\fP =48"
.br
.ti -1c
.RI "integer(c_int) \fBcategory\fP =0"
.br
.ti -1c
.RI "integer(c_int) \fBcolortype\fP =1"
.br
.ti -1c
.RI "integer(c_int) \fBcolor\fP"
.br
.ti -1c
.RI "integer(c_int) \fBpayloadtype\fP =0"
.br
.ti -1c
.RI "integer(c_int) \fBreserved0\fP"
.br
.ti -1c
.RI "integer(c_int64_t) \fBpayload\fP"
.br
.ti -1c
.RI "integer(c_int) \fBmessagetype\fP =1"
.br
.ti -1c
.RI "type(c_ptr) \fBmessage\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "integer(c_int) nvtx::nvtxeventattributes::category =0"

.SS "integer(c_int) nvtx::nvtxeventattributes::color"

.SS "integer(c_int) nvtx::nvtxeventattributes::colortype =1"

.SS "type(c_ptr) nvtx::nvtxeventattributes::message"

.SS "integer(c_int) nvtx::nvtxeventattributes::messagetype =1"

.SS "integer(c_int64_t) nvtx::nvtxeventattributes::payload"

.SS "integer(c_int) nvtx::nvtxeventattributes::payloadtype =0"

.SS "integer(c_int) nvtx::nvtxeventattributes::reserved0"

.SS "integer(c_int16_t) nvtx::nvtxeventattributes::size =48"

.SS "integer(c_int16_t) nvtx::nvtxeventattributes::version =1"


.SH "Author"
.PP 
Generated automatically by Doxygen for PaScaL_TDMA2\&.0 from the source code\&.
