.TH "/home/jihoon/Develop/PaScaL_TDMA/src/nvtx.f90" 3 "Wed Apr 26 2023" "PaScaL_TDMA2.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jihoon/Develop/PaScaL_TDMA/src/nvtx.f90
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBnvtx::nvtxeventattributes\fP"
.br
.ti -1c
.RI "interface \fBnvtx::nvtxrangepush\fP"
.br
.ti -1c
.RI "interface \fBnvtx::nvtxrangepop\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBnvtx\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBnvtx::nvtxstartrange\fP (name, id)"
.br
.ti -1c
.RI "subroutine \fBnvtx::nvtxendrange\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PaScaL_TDMA2\&.0 from the source code\&.
