.TH "nvtx" 3 "Wed Apr 26 2023" "PaScaL_TDMA2.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nvtx
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBnvtxeventattributes\fP"
.br
.ti -1c
.RI "interface \fBnvtxrangepop\fP"
.br
.ti -1c
.RI "interface \fBnvtxrangepush\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBnvtxstartrange\fP (name, id)"
.br
.ti -1c
.RI "subroutine \fBnvtxendrange\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine nvtx::nvtxendrange ()"

.SS "subroutine nvtx::nvtxstartrange (character(kind=c_char,len=*) name, integer, optional id)"

.SH "Author"
.PP 
Generated automatically by Doxygen for PaScaL_TDMA2\&.0 from the source code\&.
