.TH "/home/jihoon/Develop/PaScaL_TDMA/src/para_range.f90" 3 "Wed Apr 26 2023" "PaScaL_TDMA2.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jihoon/Develop/PaScaL_TDMA/src/para_range.f90 \- The para_range function assigns the computing range to each MPI process\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBpara_range\fP (n1, n2, nprocs, myrank, ista, iend)"
.br
.RI "Compute the indices of the assigned range for each MPI process \&. "
.in -1c
.SH "Detailed Description"
.PP 
The para_range function assigns the computing range to each MPI process\&. 


.PP
\fBAuthor:\fP
.RS 4

.IP "\(bu" 2
Kiha Kim (k-kiha@yonsei.ac.kr), Department of Computational Science & Engineering, Yonsei University
.IP "\(bu" 2
Ji-Hoon Kang (jhkang@kisti.re.kr), Korea Institute of Science and Technology Information
.IP "\(bu" 2
Jung-Il Choi (jic@yonsei.ac.kr), Department of Computational Science & Engineering, Yonsei University
.PP
.RE
.PP
\fBDate:\fP
.RS 4
June 2019 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2019-2023 Kiha Kim and Jung-Il choi, Yonsei University and Ji-Hoon Kang, Korea Institute of Science and Technology Information, All rights reserved\&. 
.RE
.PP
\fBLicense \fP
.RS 4
This project is release under the terms of the MIT License (see LICENSE in ) 
.RE
.PP

.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine para_range (integer, intent(in) n1, integer, intent(in) n2, integer, intent(in) nprocs, integer, intent(in) myrank, integer, intent(out) ista, integer, intent(out) iend)"

.PP
Compute the indices of the assigned range for each MPI process \&. 
.PP
\fBParameters:\fP
.RS 4
\fIn1\fP First index of total range 
.br
\fIn2\fP Last index of total range 
.br
\fInprocs\fP Number of MPI process 
.br
\fImyrank\fP Rank ID of my MPI process 
.br
\fIista\fP First index of assigned range for myrank 
.br
\fIiend\fP Last index of assigned range for myrank 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for PaScaL_TDMA2\&.0 from the source code\&.
